###register a new cliente
POST http://localhost:4000/api/auth/registro
Content-Type: application/json

{
  "dni": "12345678",
  "nombre": "John",
  "apellido": "Doe",
  "correo": "john.doe@example.com",
  "password": "password123",
  "confirm": "password123",
  "fecha_nacimiento": "1990-01-01",
  "genero": "M",
  "id_obra_social": 1
}

### crear cuenta nueva
POST http://localhost:4000/api/auth/registro
Content-Type: application/json

{
  "dni": "40777888",
  "nombre": "Pedro",
  "apellido": "Ruiz",
  "correo": "pedro.ruiz@mail.com",
  "password": "miclave123",
  "confirm": "miclave123",
  "fecha_nacimiento": "1995-11-02",
  "genero": "M"
}
### crear cuenta nueva
POST http://localhost:4000/api/auth/registro
Content-Type: application/json

{
  "dni": "40777886",
  "nombre": "Pedro",
  "apellido": "Ruiz",
  "password": "miclave123",
  "confirm": "miclave123",
  "fecha_nacimiento": "1995-11-02",
  "genero": "M"
}

###forgot password mail
POST http://localhost:4000/api/auth/forgot-password
Content-Type: application/json

{
  "correo": "lucalatigano12@gmail.com",
  "role": "cliente"
}

###reset password 
POST http://localhost:4000/api/auth/reset-password
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOjQ2NjY4ODE0LCJyb2xlIjoiY2xpZW50ZSIsImlhdCI6MTc4NjkyNzQxMywiZXhwIjoxNzg2OTI4MDEzfQ.Rj8nErohXoI_ctrpXSyYTirRfcCnO0kK60HKFZeQRTg",
  "password": "hola12345",
  "confirmPassword": "hola12345"
}