###iniciar sesion con un profesional
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "dni": "27845123",
  "password": "password123",
  "role": "profesional"
}

###getTurnoById
GET http://localhost:4000/api/